### ISSUE TITLE
Needs update to work on current version of HA

### ISSUE THREAD

**Issue by jbigte** [mobicek/HomeAssistant-KKRP01AClimate#1]
Thanks for this integration, looks very nice and exactly what I've been looking for.

Unfortunately it doesn't seem to work with the latest HA - eg:

Version | core-2021.9.6
Installation Type | Home Assistant Container
Development | false
Supervisor | false
Docker | true
User | root
Virtual Environment | false
Python Version | 3.9.6
Operating System Family | Linux
Operating System Version | 4.19.0-17-amd64
CPU Architecture | x86_64
Timezone | Europe/Zurich

The first fix need is easy: need to add version to manifest.json eg adding this line did the trick:

"version": "v0.0.0"

Then however I get the following error in the logs - any ideas?

2021-09-16 14:35:30 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration kkrp01a which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-09-16 14:35:30 WARNING (SyncWorker_1) [homeassistant.loader] We found a custom integration hacs which has not been tested by Home Assistant. This component might cause stability problems, be sure to disable it if you experience issues with Home Assistant
2021-09-16 14:35:31 WARNING (MainThread) [homeassistant.util.async_] Detected I/O inside the event loop. This is causing stability issues. Please report issue to the custom component author for kkrp01a doing I/O at custom_components/kkrp01a/climate.py, line 146: valuesCsv = requests.get(valuesUrl, allow_redirects=True, timeout=timeout)
2021-09-16 14:35:31 ERROR (MainThread) [homeassistant.components.climate] Error adding entities for domain climate with platform kkrp01a
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 697, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/local/lib/python3.9/asyncio/coroutines.py", line 124, in coro
res = func(*args, **kw)
File "/config/custom_components/kkrp01a/climate.py", line 396, in async_added_to_hass
self.SyncState()
File "/config/custom_components/kkrp01a/climate.py", line 237, in SyncState
currentValues = self.GetValues()
File "/config/custom_components/kkrp01a/climate.py", line 150, in GetValues
return self.FetchResult(self._ip_addr, self._timeout)
File "/config/custom_components/kkrp01a/climate.py", line 146, in FetchResult
valuesCsv = requests.get(valuesUrl, allow_redirects=True, timeout=timeout)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
return request('get', url, params=params, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.9/http/client.py", line 1257, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1268, in _send_request
self.putrequest(method, url, **skips)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 214, in putrequest
return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
check_loop()
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/kkrp01a/climate.py, line 146: valuesCsv = requests.get(valuesUrl, allow_redirects=True, timeout=timeout)
2021-09-16 14:35:31 ERROR (MainThread) [homeassistant.components.climate] Error while setting up kkrp01a platform for climate
Traceback (most recent call last):
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 257, in _async_setup_platform
await asyncio.gather(*pending)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 382, in async_add_entities
await asyncio.gather(*tasks)
File "/usr/src/homeassistant/homeassistant/helpers/entity_platform.py", line 587, in _async_add_entity
await entity.add_to_platform_finish()
File "/usr/src/homeassistant/homeassistant/helpers/entity.py", line 697, in add_to_platform_finish
await self.async_added_to_hass()
File "/usr/local/lib/python3.9/asyncio/coroutines.py", line 124, in coro
res = func(*args, **kw)
File "/config/custom_components/kkrp01a/climate.py", line 396, in async_added_to_hass
self.SyncState()
File "/config/custom_components/kkrp01a/climate.py", line 237, in SyncState
currentValues = self.GetValues()
File "/config/custom_components/kkrp01a/climate.py", line 150, in GetValues
return self.FetchResult(self._ip_addr, self._timeout)
File "/config/custom_components/kkrp01a/climate.py", line 146, in FetchResult
valuesCsv = requests.get(valuesUrl, allow_redirects=True, timeout=timeout)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 76, in get
return request('get', url, params=params, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/api.py", line 61, in request
return session.request(method=method, url=url, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 542, in request
resp = self.send(prep, **send_kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/sessions.py", line 655, in send
r = adapter.send(request, **kwargs)
File "/usr/local/lib/python3.9/site-packages/requests/adapters.py", line 439, in send
resp = conn.urlopen(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 699, in urlopen
httplib_response = self._make_request(
File "/usr/local/lib/python3.9/site-packages/urllib3/connectionpool.py", line 394, in _make_request
conn.request(method, url, **httplib_request_kw)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 234, in request
super(HTTPConnection, self).request(method, url, body=body, headers=headers)
File "/usr/local/lib/python3.9/http/client.py", line 1257, in request
self._send_request(method, url, body, headers, encode_chunked)
File "/usr/local/lib/python3.9/http/client.py", line 1268, in _send_request
self.putrequest(method, url, **skips)
File "/usr/local/lib/python3.9/site-packages/urllib3/connection.py", line 214, in putrequest
return _HTTPConnection.putrequest(self, method, url, *args, **kwargs)
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 151, in protected_loop_func
check_loop()
File "/usr/src/homeassistant/homeassistant/util/async_.py", line 140, in check_loop
raise RuntimeError(
RuntimeError: I/O must be done in the executor; Use `await hass.async_add_executor_job()` at custom_components/kkrp01a/climate.py, line 146: valuesCsv = requests.get(valuesUrl, allow_redirects=True, timeout=timeout)

**Comment by asenshristov-collab** [comment]
Is there hope it will be updated :)

**Comment by jbigte** [comment]
I’ve now made some fixes and submitted pull requests for them. The changes are working correctly on my setup with Home Assistant Container, Core 2026.5.1, and Frontend 20260429.3.
